# Generated by Django 4.0.6 on 2022-10-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_response_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='ads.post'),
        ),
    ]
