# Generated by Django 4.0.6 on 2022-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_response_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
